// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package improvmx

import (
	"context"
	"reflect"

	"errors"
	"github.com/lokkju/pulumi-improvmx/sdk/go/improvmx/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages an ImprovMX email alias (forwarding rule).
type EmailAlias struct {
	pulumi.CustomResourceState

	// The alias name (e.g., 'info', '*' for catch-all).
	Alias pulumi.StringOutput `pulumi:"alias"`
	// The domain this alias belongs to.
	Domain pulumi.StringOutput `pulumi:"domain"`
	// Comma-separated destination email addresses.
	Forward pulumi.StringOutput `pulumi:"forward"`
}

// NewEmailAlias registers a new resource with the given unique name, arguments, and options.
func NewEmailAlias(ctx *pulumi.Context,
	name string, args *EmailAliasArgs, opts ...pulumi.ResourceOption) (*EmailAlias, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Alias == nil {
		return nil, errors.New("invalid value for required argument 'Alias'")
	}
	if args.Domain == nil {
		return nil, errors.New("invalid value for required argument 'Domain'")
	}
	if args.Forward == nil {
		return nil, errors.New("invalid value for required argument 'Forward'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource EmailAlias
	err := ctx.RegisterResource("improvmx:index:EmailAlias", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetEmailAlias gets an existing EmailAlias resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetEmailAlias(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *EmailAliasState, opts ...pulumi.ResourceOption) (*EmailAlias, error) {
	var resource EmailAlias
	err := ctx.ReadResource("improvmx:index:EmailAlias", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering EmailAlias resources.
type emailAliasState struct {
}

type EmailAliasState struct {
}

func (EmailAliasState) ElementType() reflect.Type {
	return reflect.TypeOf((*emailAliasState)(nil)).Elem()
}

type emailAliasArgs struct {
	// The alias name (e.g., 'info', '*' for catch-all).
	Alias string `pulumi:"alias"`
	// The domain this alias belongs to.
	Domain string `pulumi:"domain"`
	// Comma-separated destination email addresses.
	Forward string `pulumi:"forward"`
}

// The set of arguments for constructing a EmailAlias resource.
type EmailAliasArgs struct {
	// The alias name (e.g., 'info', '*' for catch-all).
	Alias pulumi.StringInput
	// The domain this alias belongs to.
	Domain pulumi.StringInput
	// Comma-separated destination email addresses.
	Forward pulumi.StringInput
}

func (EmailAliasArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*emailAliasArgs)(nil)).Elem()
}

type EmailAliasInput interface {
	pulumi.Input

	ToEmailAliasOutput() EmailAliasOutput
	ToEmailAliasOutputWithContext(ctx context.Context) EmailAliasOutput
}

func (*EmailAlias) ElementType() reflect.Type {
	return reflect.TypeOf((**EmailAlias)(nil)).Elem()
}

func (i *EmailAlias) ToEmailAliasOutput() EmailAliasOutput {
	return i.ToEmailAliasOutputWithContext(context.Background())
}

func (i *EmailAlias) ToEmailAliasOutputWithContext(ctx context.Context) EmailAliasOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EmailAliasOutput)
}

// EmailAliasArrayInput is an input type that accepts EmailAliasArray and EmailAliasArrayOutput values.
// You can construct a concrete instance of `EmailAliasArrayInput` via:
//
//	EmailAliasArray{ EmailAliasArgs{...} }
type EmailAliasArrayInput interface {
	pulumi.Input

	ToEmailAliasArrayOutput() EmailAliasArrayOutput
	ToEmailAliasArrayOutputWithContext(context.Context) EmailAliasArrayOutput
}

type EmailAliasArray []EmailAliasInput

func (EmailAliasArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*EmailAlias)(nil)).Elem()
}

func (i EmailAliasArray) ToEmailAliasArrayOutput() EmailAliasArrayOutput {
	return i.ToEmailAliasArrayOutputWithContext(context.Background())
}

func (i EmailAliasArray) ToEmailAliasArrayOutputWithContext(ctx context.Context) EmailAliasArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EmailAliasArrayOutput)
}

// EmailAliasMapInput is an input type that accepts EmailAliasMap and EmailAliasMapOutput values.
// You can construct a concrete instance of `EmailAliasMapInput` via:
//
//	EmailAliasMap{ "key": EmailAliasArgs{...} }
type EmailAliasMapInput interface {
	pulumi.Input

	ToEmailAliasMapOutput() EmailAliasMapOutput
	ToEmailAliasMapOutputWithContext(context.Context) EmailAliasMapOutput
}

type EmailAliasMap map[string]EmailAliasInput

func (EmailAliasMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*EmailAlias)(nil)).Elem()
}

func (i EmailAliasMap) ToEmailAliasMapOutput() EmailAliasMapOutput {
	return i.ToEmailAliasMapOutputWithContext(context.Background())
}

func (i EmailAliasMap) ToEmailAliasMapOutputWithContext(ctx context.Context) EmailAliasMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EmailAliasMapOutput)
}

type EmailAliasOutput struct{ *pulumi.OutputState }

func (EmailAliasOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**EmailAlias)(nil)).Elem()
}

func (o EmailAliasOutput) ToEmailAliasOutput() EmailAliasOutput {
	return o
}

func (o EmailAliasOutput) ToEmailAliasOutputWithContext(ctx context.Context) EmailAliasOutput {
	return o
}

// The alias name (e.g., 'info', '*' for catch-all).
func (o EmailAliasOutput) Alias() pulumi.StringOutput {
	return o.ApplyT(func(v *EmailAlias) pulumi.StringOutput { return v.Alias }).(pulumi.StringOutput)
}

// The domain this alias belongs to.
func (o EmailAliasOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v *EmailAlias) pulumi.StringOutput { return v.Domain }).(pulumi.StringOutput)
}

// Comma-separated destination email addresses.
func (o EmailAliasOutput) Forward() pulumi.StringOutput {
	return o.ApplyT(func(v *EmailAlias) pulumi.StringOutput { return v.Forward }).(pulumi.StringOutput)
}

type EmailAliasArrayOutput struct{ *pulumi.OutputState }

func (EmailAliasArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*EmailAlias)(nil)).Elem()
}

func (o EmailAliasArrayOutput) ToEmailAliasArrayOutput() EmailAliasArrayOutput {
	return o
}

func (o EmailAliasArrayOutput) ToEmailAliasArrayOutputWithContext(ctx context.Context) EmailAliasArrayOutput {
	return o
}

func (o EmailAliasArrayOutput) Index(i pulumi.IntInput) EmailAliasOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *EmailAlias {
		return vs[0].([]*EmailAlias)[vs[1].(int)]
	}).(EmailAliasOutput)
}

type EmailAliasMapOutput struct{ *pulumi.OutputState }

func (EmailAliasMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*EmailAlias)(nil)).Elem()
}

func (o EmailAliasMapOutput) ToEmailAliasMapOutput() EmailAliasMapOutput {
	return o
}

func (o EmailAliasMapOutput) ToEmailAliasMapOutputWithContext(ctx context.Context) EmailAliasMapOutput {
	return o
}

func (o EmailAliasMapOutput) MapIndex(k pulumi.StringInput) EmailAliasOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *EmailAlias {
		return vs[0].(map[string]*EmailAlias)[vs[1].(string)]
	}).(EmailAliasOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*EmailAliasInput)(nil)).Elem(), &EmailAlias{})
	pulumi.RegisterInputType(reflect.TypeOf((*EmailAliasArrayInput)(nil)).Elem(), EmailAliasArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*EmailAliasMapInput)(nil)).Elem(), EmailAliasMap{})
	pulumi.RegisterOutputType(EmailAliasOutput{})
	pulumi.RegisterOutputType(EmailAliasArrayOutput{})
	pulumi.RegisterOutputType(EmailAliasMapOutput{})
}
