// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package improvmx

import (
	"context"
	"reflect"

	"errors"
	"github.com/lokkju/pulumi-improvmx/sdk/go/improvmx/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages an ImprovMX SMTP credential for sending email.
type SmtpCredential struct {
	pulumi.CustomResourceState

	// Unix timestamp when the credential was created.
	Created pulumi.IntOutput `pulumi:"created"`
	// The domain this SMTP credential belongs to.
	Domain pulumi.StringOutput `pulumi:"domain"`
	// The SMTP password.
	Password pulumi.StringOutput `pulumi:"password"`
	// The SMTP username.
	Username pulumi.StringOutput `pulumi:"username"`
}

// NewSmtpCredential registers a new resource with the given unique name, arguments, and options.
func NewSmtpCredential(ctx *pulumi.Context,
	name string, args *SmtpCredentialArgs, opts ...pulumi.ResourceOption) (*SmtpCredential, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Domain == nil {
		return nil, errors.New("invalid value for required argument 'Domain'")
	}
	if args.Password == nil {
		return nil, errors.New("invalid value for required argument 'Password'")
	}
	if args.Username == nil {
		return nil, errors.New("invalid value for required argument 'Username'")
	}
	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"password",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SmtpCredential
	err := ctx.RegisterResource("improvmx:index:SmtpCredential", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSmtpCredential gets an existing SmtpCredential resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSmtpCredential(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SmtpCredentialState, opts ...pulumi.ResourceOption) (*SmtpCredential, error) {
	var resource SmtpCredential
	err := ctx.ReadResource("improvmx:index:SmtpCredential", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SmtpCredential resources.
type smtpCredentialState struct {
}

type SmtpCredentialState struct {
}

func (SmtpCredentialState) ElementType() reflect.Type {
	return reflect.TypeOf((*smtpCredentialState)(nil)).Elem()
}

type smtpCredentialArgs struct {
	// The domain this SMTP credential belongs to.
	Domain string `pulumi:"domain"`
	// The SMTP password.
	Password string `pulumi:"password"`
	// The SMTP username.
	Username string `pulumi:"username"`
}

// The set of arguments for constructing a SmtpCredential resource.
type SmtpCredentialArgs struct {
	// The domain this SMTP credential belongs to.
	Domain pulumi.StringInput
	// The SMTP password.
	Password pulumi.StringInput
	// The SMTP username.
	Username pulumi.StringInput
}

func (SmtpCredentialArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*smtpCredentialArgs)(nil)).Elem()
}

type SmtpCredentialInput interface {
	pulumi.Input

	ToSmtpCredentialOutput() SmtpCredentialOutput
	ToSmtpCredentialOutputWithContext(ctx context.Context) SmtpCredentialOutput
}

func (*SmtpCredential) ElementType() reflect.Type {
	return reflect.TypeOf((**SmtpCredential)(nil)).Elem()
}

func (i *SmtpCredential) ToSmtpCredentialOutput() SmtpCredentialOutput {
	return i.ToSmtpCredentialOutputWithContext(context.Background())
}

func (i *SmtpCredential) ToSmtpCredentialOutputWithContext(ctx context.Context) SmtpCredentialOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SmtpCredentialOutput)
}

// SmtpCredentialArrayInput is an input type that accepts SmtpCredentialArray and SmtpCredentialArrayOutput values.
// You can construct a concrete instance of `SmtpCredentialArrayInput` via:
//
//	SmtpCredentialArray{ SmtpCredentialArgs{...} }
type SmtpCredentialArrayInput interface {
	pulumi.Input

	ToSmtpCredentialArrayOutput() SmtpCredentialArrayOutput
	ToSmtpCredentialArrayOutputWithContext(context.Context) SmtpCredentialArrayOutput
}

type SmtpCredentialArray []SmtpCredentialInput

func (SmtpCredentialArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SmtpCredential)(nil)).Elem()
}

func (i SmtpCredentialArray) ToSmtpCredentialArrayOutput() SmtpCredentialArrayOutput {
	return i.ToSmtpCredentialArrayOutputWithContext(context.Background())
}

func (i SmtpCredentialArray) ToSmtpCredentialArrayOutputWithContext(ctx context.Context) SmtpCredentialArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SmtpCredentialArrayOutput)
}

// SmtpCredentialMapInput is an input type that accepts SmtpCredentialMap and SmtpCredentialMapOutput values.
// You can construct a concrete instance of `SmtpCredentialMapInput` via:
//
//	SmtpCredentialMap{ "key": SmtpCredentialArgs{...} }
type SmtpCredentialMapInput interface {
	pulumi.Input

	ToSmtpCredentialMapOutput() SmtpCredentialMapOutput
	ToSmtpCredentialMapOutputWithContext(context.Context) SmtpCredentialMapOutput
}

type SmtpCredentialMap map[string]SmtpCredentialInput

func (SmtpCredentialMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SmtpCredential)(nil)).Elem()
}

func (i SmtpCredentialMap) ToSmtpCredentialMapOutput() SmtpCredentialMapOutput {
	return i.ToSmtpCredentialMapOutputWithContext(context.Background())
}

func (i SmtpCredentialMap) ToSmtpCredentialMapOutputWithContext(ctx context.Context) SmtpCredentialMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SmtpCredentialMapOutput)
}

type SmtpCredentialOutput struct{ *pulumi.OutputState }

func (SmtpCredentialOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SmtpCredential)(nil)).Elem()
}

func (o SmtpCredentialOutput) ToSmtpCredentialOutput() SmtpCredentialOutput {
	return o
}

func (o SmtpCredentialOutput) ToSmtpCredentialOutputWithContext(ctx context.Context) SmtpCredentialOutput {
	return o
}

// Unix timestamp when the credential was created.
func (o SmtpCredentialOutput) Created() pulumi.IntOutput {
	return o.ApplyT(func(v *SmtpCredential) pulumi.IntOutput { return v.Created }).(pulumi.IntOutput)
}

// The domain this SMTP credential belongs to.
func (o SmtpCredentialOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v *SmtpCredential) pulumi.StringOutput { return v.Domain }).(pulumi.StringOutput)
}

// The SMTP password.
func (o SmtpCredentialOutput) Password() pulumi.StringOutput {
	return o.ApplyT(func(v *SmtpCredential) pulumi.StringOutput { return v.Password }).(pulumi.StringOutput)
}

// The SMTP username.
func (o SmtpCredentialOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v *SmtpCredential) pulumi.StringOutput { return v.Username }).(pulumi.StringOutput)
}

type SmtpCredentialArrayOutput struct{ *pulumi.OutputState }

func (SmtpCredentialArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SmtpCredential)(nil)).Elem()
}

func (o SmtpCredentialArrayOutput) ToSmtpCredentialArrayOutput() SmtpCredentialArrayOutput {
	return o
}

func (o SmtpCredentialArrayOutput) ToSmtpCredentialArrayOutputWithContext(ctx context.Context) SmtpCredentialArrayOutput {
	return o
}

func (o SmtpCredentialArrayOutput) Index(i pulumi.IntInput) SmtpCredentialOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SmtpCredential {
		return vs[0].([]*SmtpCredential)[vs[1].(int)]
	}).(SmtpCredentialOutput)
}

type SmtpCredentialMapOutput struct{ *pulumi.OutputState }

func (SmtpCredentialMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SmtpCredential)(nil)).Elem()
}

func (o SmtpCredentialMapOutput) ToSmtpCredentialMapOutput() SmtpCredentialMapOutput {
	return o
}

func (o SmtpCredentialMapOutput) ToSmtpCredentialMapOutputWithContext(ctx context.Context) SmtpCredentialMapOutput {
	return o
}

func (o SmtpCredentialMapOutput) MapIndex(k pulumi.StringInput) SmtpCredentialOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SmtpCredential {
		return vs[0].(map[string]*SmtpCredential)[vs[1].(string)]
	}).(SmtpCredentialOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SmtpCredentialInput)(nil)).Elem(), &SmtpCredential{})
	pulumi.RegisterInputType(reflect.TypeOf((*SmtpCredentialArrayInput)(nil)).Elem(), SmtpCredentialArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SmtpCredentialMapInput)(nil)).Elem(), SmtpCredentialMap{})
	pulumi.RegisterOutputType(SmtpCredentialOutput{})
	pulumi.RegisterOutputType(SmtpCredentialArrayOutput{})
	pulumi.RegisterOutputType(SmtpCredentialMapOutput{})
}
